#define GOOBYTERM_INITIAL_WIDTH  640
#define GOOBYTERM_INITIAL_HEIGHT 480

#ifndef GOOBYTERM_WHITELIST
#define GOOBYRERM_WHITELIST { "example.com" }
#endif

#ifndef GOOBYTERM_FAVICON_SIZE
#define GOOBYTERM_FAVICON_SIZE 16
#endif
